version: '3.8'

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8080 project.wsgi:application"
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    env_file: .env
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_data:/app/staticfiles 
      - media_data:/app/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
  static_data:
  media_data:
