# Generated by Django 4.2.4 on 2023-08-16 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.IntegerField(verbose_name='цена цветка')),
            ],
            options={
                'verbose_name': 'цветок',
                'verbose_name_plural': 'цветы',
            },
        ),
        migrations.CreateModel(
            name='FlowerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='число')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_set', to='flower_shop.flower', verbose_name='набор цветов')),
            ],
            options={
                'verbose_name': 'набор цветов',
                'verbose_name_plural': 'наборы цветов',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers_sets',
            field=models.ManyToManyField(related_name='bouquet', to='flower_shop.flowerset', verbose_name='наборы цветов'),
        ),
    ]
