# Generated by Django 4.2.4 on 2023-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0002_flower_flowerset_bouquet_flowers_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(default=0, verbose_name='высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(default=0, verbose_name='ширина'),
            preserve_default=False,
        ),
    ]
