# Generated by Django 4.2.4 on 2023-08-17 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0003_bouquet_height_bouquet_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='flowerset',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='число'),
        ),
    ]
