# Generated by Django 4.2.4 on 2023-08-17 20:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0005_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('preferred_delivery_time', models.CharField(max_length=50, verbose_name='желаемое время доставки')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.bouquet', verbose_name='букет')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
