# Generated by Django 4.2.4 on 2023-08-19 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0011_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='max_price',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='максимальная цена'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='min_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='минимальная цена'),
        ),
    ]
