# Generated by Django 4.2.4 on 2023-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0012_alter_budget_max_price_alter_budget_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='does_metter',
            field=models.BooleanField(default=True, verbose_name='имеет значение'),
        ),
    ]
