# Generated by Django 4.2.4 on 2023-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0013_budget_does_metter'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='обработан'),
        ),
    ]
